# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: ENV["my_admin_name"]
  admin_email: ENV["my_admin_email"]
  admin_password: ENV["my_admin_password"]
  email_provider_username: ENV["my_email_provider_username"]
  email_provider_password: ENV["my_email_provider_password"]
  domain_name: ENV["my_domain_name"]
  secret_key_base: ENV["my_secret_key_base"]

test:
  domain_name: ENV["my_domain_name"]
  secret_key_base: ENV["my_secret_key_base"]

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: ENV["my_admin_name"]
  admin_email: ENV["my_admin_email"]
  admin_password: ENV["my_admin_password"]
  email_provider_username: ENV["my_email_provider_username"]
  email_provider_password: ENV["my_email_provider_password"]
  domain_name: ENV["my_domain_name"]
  secret_key_base: ENV["my_secret_key_base"]